### ISSUE TITLE
[Enhancement] Add playcoin bank

### ISSUE THREAD

**Issue by Ixolaro** [t0xid/For-Anyone-Who-Walks-Revamp#1]
Hey, i wanted to know if a play coin bank to bypass 300 coin limit is possible
thanks

**Comment by t0xid** [comment]
what do you mean by a bank?

**Comment by Ixolaro** [comment]
On the original for-any-one-who-walks-a-lot i think the developer planned a way to deposit and withdraw play coins in a playcoin bank to bypass 300 coin limit

**Comment by t0xid** [comment]
hmmm. could modify the way it saves to the cache file.
just briefly looking at the code it limits the files size of the cache to 8 bytes. 
could add more fields and stuff to save to the file and increase its size. i just dont know alot about file modification with C

**Comment by t0xid** [comment]
looking to see if i can rig something together

**Comment by t0xid** [comment]
ok. figured out a system. idk if its optimized enough, but it works

**Comment by Ixolaro** [comment]
yay thanks. also if i may ask whats ur discord? if u have discord

**Comment by t0xid** [comment]
why?
